; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; --- Branding ---
AppName=WhiteoutProjectOS
DefaultDirName={autopf}\WhiteoutProjectOS
DefaultGroupName=WhiteoutProjectOS

; --- 1. Control Panel / Add & Remove Programs Metadata ---
AppVersion=1.0.0
AppPublisher=Whiteout Project Team
AppPublisherURL=https://github.com/whiteout-project
AppSupportURL=https://github.com/whiteout-project/os/issues
AppUpdatesURL=https://github.com/whiteout-project/os/releases
AppCopyright=Copyright (C) 2026 Whiteout Project Team

; --- 2. Windows Executable Metadata (Right-Click -> Properties) ---
VersionInfoVersion=1.0.0.0
VersionInfoCompany=Whiteout Project Team
VersionInfoDescription=WhiteoutProjectOS Installer System
VersionInfoProductName=WhiteoutProjectOS
VersionInfoCopyright=Copyright (C) 2026 Whiteout Project Team

; --- 3. UI Polish ---
; This automatically uninstalls the old version if they run a newer installer!
SetupLogging=yes
CloseApplications=yes
RestartApplications=no

; --- The Magic Icons ---
; This guarantees the installer file itself has your shield!
SetupIconFile=icon.ico 
; This makes the wizard look incredibly professional
WizardSmallImageFile=logo.png

; --- Output ---
OutputDir=userdocs
OutputBaseFilename=WhiteoutProjectOS_Installer
Compression=lzma
SolidCompression=yes

[Files]
; 1. Add this NEW line to extract the Go app to a hidden temp folder for the pre-flight check
Source: "WhiteoutProjectOS.exe"; DestDir: "{tmp}"; Flags: dontcopy

; 2. Keep your existing line so it actually gets installed to Program Files if the check passes
Source: "WhiteoutProjectOS.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[INI]
; Saves the username from your existing Credentials page into a config file
Filename: "{app}\config.ini"; Section: "System"; Key: "Username"; String: "{code:GetUsername}"

[Icons]
; 1. The Start Menu Shortcut
Name: "{autoprograms}\WhiteoutProjectOS"; Filename: "{app}\WhiteoutProjectOS.exe"; Parameters: "-launch"; IconFilename: "{app}\icon.ico"

; 2. The Desktop Shortcut 
Name: "{autodesktop}\WhiteoutProjectOS"; Filename: "{app}\WhiteoutProjectOS.exe"; Parameters: "-launch"; IconFilename: "{app}\icon.ico"; Tasks: desktopicon

[Run]
; Runs the Installer Mode silently while the setup wizard is finishing
Filename: "{app}\WhiteoutProjectOS.exe"; Parameters: "-launch"; Description: "Launch WhiteoutProjectOS"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; When the user uninstalls from the Windows Control Panel, this wipes the WSL distro!
Filename: "{app}\WhiteoutProjectOS.exe"; Parameters: "-uninstall"; RunOnceId: "RemoveWSL"

[Code]
var
  CredentialsPage: TInputQueryWizardPage;

// 1. BUILD THE CUSTOM UI PAGE
procedure InitializeWizard;
begin
  CredentialsPage := CreateInputQueryPage(wpWelcome,
    'Server Credentials', 'Please enter your background server details.',
    'Configure Linux Subsystem credentials or click next to use the default.');
    
  CredentialsPage.Add('Username:', False);
  CredentialsPage.Add('Password: (Default: Password123)', True);
  CredentialsPage.Add('Confirm Password:', True);
  CredentialsPage.Add('Hostname:', False);

  CredentialsPage.Values[0] := 'wp-os-user';
  CredentialsPage.Values[1] := ''; 
  CredentialsPage.Values[2] := ''; 
  CredentialsPage.Values[3] := 'wp-os-server';
end;

// 2. DEFINE THE EXTRACTION FUNCTIONS
function GetUsername(Param: String): String;
begin
  if Trim(CredentialsPage.Values[0]) = '' then Result := 'wp-os-user'
  else Result := CredentialsPage.Values[0];
end;

function GetPassword(Param: String): String;
begin
  if CredentialsPage.Values[1] = '' then Result := 'Password123'
  else Result := CredentialsPage.Values[1];
end;

function GetHostname(Param: String): String;
begin
  if Trim(CredentialsPage.Values[3]) = '' then Result := 'wp-os-server'
  else Result := CredentialsPage.Values[3];
end;

// 3. THE 4-STAGE PROGRESSIVE INSTALLATION
function NextButtonClick(CurPageID: Integer): Boolean;
var
  ResultCode: Integer;
  Parameters: String;
  ProgressPage: TOutputProgressWizardPage;
begin
  Result := True;

  // --- VALIDATION PHASE ---
  if CurPageID = CredentialsPage.ID then
  begin
    if CredentialsPage.Values[1] <> CredentialsPage.Values[2] then
    begin
      MsgBox('Passwords do not match. Please make sure both password fields are identical.', mbError, MB_OK);
      Result := False;
      Exit;
    end;
  end;

  // --- PRE-FLIGHT & INSTALLATION PHASE ---
  if CurPageID = wpReady then
  begin
    ExtractTemporaryFile('WhiteoutProjectOS.exe');

    ProgressPage := CreateOutputProgressPage('System Installation', 'Configuring required environments...');
    
    // THIS FIXES THE INVISIBLE BAR: 
    // Calling SetProgress triggers Inno Setup to make the bar visible on the screen.
    ProgressPage.SetProgress(0, 100); 
    ProgressPage.Show;
    try

      // --- STAGE 1 ---
      ProgressPage.SetText('Enabling Windows Subsystem for Linux (WSL)...', 'Configuring Windows core features.');
      if Exec(ExpandConstant('{tmp}\WhiteoutProjectOS.exe'), '-stage1', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
      begin
        if ResultCode <> 0 then begin Result := False; Exit; end;
      end
      else begin MsgBox('Fatal Error: Stage 1 failed.', mbError, MB_OK); Result := False; Exit; end;
      
      ProgressPage.SetProgress(25, 100); // Updates the green bar to 25%

      // --- STAGE 2 ---
      ProgressPage.SetText('Enabling Virtual Machine Platform...', 'Configuring hypervisor capabilities.');
      if Exec(ExpandConstant('{tmp}\WhiteoutProjectOS.exe'), '-stage2', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
      begin
        if ResultCode <> 0 then begin Result := False; Exit; end;
      end
      else begin MsgBox('Fatal Error: Stage 2 failed.', mbError, MB_OK); Result := False; Exit; end;

      ProgressPage.SetProgress(50, 100); // Updates the green bar to 50%

      // --- STAGE 3 ---
      ProgressPage.SetText('Installing Ubuntu on WSL...', 'Downloading and registering the Linux distribution. This may take a moment.');
      if Exec(ExpandConstant('{tmp}\WhiteoutProjectOS.exe'), '-stage3', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
      begin
        if ResultCode <> 0 then begin Result := False; Exit; end; 
      end
      else begin MsgBox('Fatal Error: Stage 3 failed.', mbError, MB_OK); Result := False; Exit; end;

      ProgressPage.SetProgress(75, 100); // Updates the green bar to 75%

      // --- STAGE 4 ---
      ProgressPage.SetText('Installing WhiteoutProjectOS...', 'Downloading and configuring backend OS services.');
      Parameters := '-stage4 "' + GetUsername('') + '" "' + GetPassword('') + '" "' + GetHostname('') + '"';
      if Exec(ExpandConstant('{tmp}\WhiteoutProjectOS.exe'), Parameters, '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
      begin
        if ResultCode <> 0 then begin Result := False; Exit; end;
      end
      else begin MsgBox('Fatal Error: Stage 4 failed.', mbError, MB_OK); Result := False; Exit; end;

      ProgressPage.SetProgress(100, 100); // Bar hits 100%
      
      Sleep(500); // Brief pause so the user actually sees it finish

    finally
      ProgressPage.Hide; 
    end;
  end;
end;